# Generated by Django 5.0.6 on 2024-10-22 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_files_user_alter_files_uploaded_at_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='file',
            new_name='uploaded_file',
        ),
    ]
